source 'https://rubygems.org'
gem 'thor'
gem 'sys-filesystem'
gem 'sys-cpu'
gem 'mail', '2.5.3'
gem 'httparty', '~> 0.11.0'
gem 'hipchat', '~>0.12.0'
gem 'statsd-ruby'
gem 'hashie'
gem 'os'
gem 'pagerduty'
